spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.151.7:3306/orion_visor?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai&autoReconnect=true
      username: root
      password: gvs@2021
      initial-size: 0
      min-idle: 1
      max-active: 5
  redis:
    host: 192.168.151.233
    port: 6379
    password: gvs@2021
    database: 2
  redisson:
    threads: 2
    netty-threads: 2

mybatis-plus:
  configuration:
    # 日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
